# Generated by Django 5.2.4 on 2025-07-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="status",
            field=models.CharField(
                choices=[("CR", "Created"), ("OR", "Ordered")],
                default="CR",
                max_length=7,
            ),
        ),
    ]
