# Generated by Django 5.2.4 on 2025-07-03 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("UK", "United Kingdom"),
                            ("DE", "Germany"),
                            ("FR", "France"),
                            ("PL", "Poland"),
                            ("NL", "Netherlands"),
                        ],
                        max_length=2,
                    ),
                ),
                ("order_date", models.DateTimeField(auto_now_add=True)),
                (
                    "carts",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="cart.cart",
                    ),
                ),
            ],
        ),
    ]
